"""empty message

Revision ID: e80745022e1b
Revises: 
Create Date: 2023-05-07 21:39:35.726578

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e80745022e1b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("username", sa.String(length=75), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("salt", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_id"), "accounts", ["id"], unique=False)
    op.create_index(
        op.f("ix_accounts_username"), "accounts", ["username"], unique=False
    )
    op.create_table(
        "unit_types",
        sa.Column("unit", sa.String(length=75), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_unit_types_id"), "unit_types", ["id"], unique=False)
    op.create_index(op.f("ix_unit_types_unit"), "unit_types", ["unit"], unique=False)
    op.create_table(
        "ingredients",
        sa.Column("title", sa.String(length=75), nullable=False),
        sa.Column("summary", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("expired_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("unittype_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unittype_id"],
            ["unit_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredients_id"), "ingredients", ["id"], unique=False)
    op.create_index(
        op.f("ix_ingredients_title"), "ingredients", ["title"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingredients_title"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_id"), table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_unit_types_unit"), table_name="unit_types")
    op.drop_index(op.f("ix_unit_types_id"), table_name="unit_types")
    op.drop_table("unit_types")
    op.drop_index(op.f("ix_accounts_username"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
